### ISSUE TITLE
Run train.bat

### ISSUE THREAD

**Issue by formeo14** [zomiotek/Faster-R-CNN-for-Animals-Detection#1]
I'm eager to test your code, but I have a couple of queries. When I attempt to run the `train.bat` file, I encounter the following error:

```
"...\LocalCache\local-packages\Python312\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Additionally, I'm unsure about the correct location to save the dataset and reference it in the command. For the repository at https://github.com/trzy/FasterRCNN, there was a `--dataset-dir` option. Does your code also support this?

Lastly, is there a quick method to install all required packages? Using `pip install -r ***.txt` doesn't seem to be feasible.

**Comment by zomiotek** [comment]
If you work under Windows and use Anaconda, my advice is this:
– Create a virtual environment with Python 3.10.
– Install PyTorch:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
– Install the remaining libraries. The most important include: h5py, imageio, matplotlib, numpy, tqdm. You can't do it on the basis of a packages.txt file because it's not a requirements.txt file, but you can prepare such a file on its basis. You can also install libraries one by one.
– The Faster-R-CNN-for-Dangerous-Items-Detection-main.zip archive should be unpacked into the user's home directory. On Windows, it will be C:\Users\UserName\...
– The dataset directory containing the data should be copied directly to the Faster-R-CNN-for-Dangerous-Items-Detection-main directory.
– Then, in the Anaconda Prompt console, go to the Faster-R-CNN-for-Dangerous-Items-Detection-main: cd Faster-R-CNN-for-Dangerous-Items-Detection-main
– Now you just need to run one of the 3 batch files – coarse training (train.bat), fine tuning (tune.bat), evaluation (eval.bat). I introduced batch files instead of typing a long command into the console, because it turned out to be more convenient at the stage of modifying the code.
– All input arguments should be supported. In the __main__.py file, you can set default values to shorten the command used to run. For example, I set the location of the data directory to dataset, i.e. directly in the working directory. You can experiment.

Here's an example of what's included in requirements.txt:
h5py==3.11.0
imageio==2.34.2
matplotlib==3.9.0
numpy==1.26.3
tqdm==4.66.4
opencv-python==4.10.0.84
pandas==2.2.2
Pillow==9.3.0
You can use such a file in the command: pip install -r requirements.txt

**Comment by formeo14** [comment]
Thanks for the help! 
Everything's working fine now, except for a missing log file .csv after training when testing the model. I'm sure that's easy to fix.

Thanks again for explaining everything so well!

**Comment by zomiotek** [comment]
The log files from both stages of training are saved in the log directory under the names training_metrics_1.csv and training_metrics_1.csv. After merging their content, you can draw training losses and mAP graphs.

**Comment by formeo14** [comment]
I already thought that the log files are to be visualized later. The problem is not with the log files but with the fact that they are not created. So for now I will disable them:
Epoch 1/10
100%|█| 450/450 [03:21<00:00,  1.18it/s, rpn_class_loss=0.2461, rpn_regr_loss=0.0548, detector_class_loss=0.4529, detec
Evaluating 'test'...
 99%|███████████████████████████████████████████████████████████████████████████████▍| 149/150 [00:46<00:00,  3.23it/s]
Mean Average Precision = 21.31%
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Faster-R-CNN-for-Animals-Detection-main\FasterRCNN\__main__.py", line 329, in <module>
    train(model = model)
  File "C:\Users\admin\Faster-R-CNN-for-Animals-Detection-main\FasterRCNN\__main__.py", line 218, in train
    csv.log(log_items)
  File "C:\Users\admin\Faster-R-CNN-for-Animals-Detection-main\FasterRCNN\utils.py", line 24, in log
    with open(self._filename, file_mode) as fp:
FileNotFoundError: [Errno 2] No such file or directory: './log/training_metrics_1.csv'

**Comment by formeo14** [comment]
I changed your utils and now it saves the log files
[utils.py.txt](https://github.com/user-attachments/files/16279102/utils.py.txt)

But now it doesn't save the model, because the directory will not be automatically created :
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Faster-R-CNN-for-Animals-Detection-main\FasterRCNN\__main__.py", line 329, in <module>
    train(model = model)
  File "C:\Users\admin\Faster-R-CNN-for-Animals-Detection-main\FasterRCNN\__main__.py", line 221, in train
    best_weights_tracker.save_best_weights(model = model, epoch = epoch)
  File "C:\Users\admin\Faster-R-CNN-for-Animals-Detection-main\FasterRCNN\state.py", line 283, in save_best_weights
    t.save(self._best_state, self._filepath + "_" + str(epoch))
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\site-packages\torch\serialization.py", line 627, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\site-packages\torch\serialization.py", line 501, in _open_zipfile_writer
    return container(name_or_buffer)
  File "C:\Users\admin\miniconda3\envs\faster-r-cnn-for-animals-detection\lib\site-packages\torch\serialization.py", line 472, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory ./models does not exist.


So I added to the state.py these lines 283: 
```py
 def save_best_weights(self, model, epoch):
    directory = os.path.dirname(self._filepath)
    if not os.path.exists(directory):
      os.makedirs(directory)

    save_path = self._filepath + "_" + str(epoch)
    t.save(self._best_state, save_path)
    print("Saved model weights to " + save_path)```

**Comment by zomiotek** [comment]
I know what the problem is When uploading the code to GitHub, empty directories were not created (my mistake). Create directories: log, models and pred.
![screen](https://github.com/user-attachments/assets/f4f3697e-67f5-4609-8f73-e0a0b6e3268e)

**Comment by formeo14** [comment]
I modified the code to ensure it creates the directories automatically. It runs now... hopefully ;)
